### ISSUE TITLE
Support Canonical Path Resolution for <script>

### ISSUE THREAD

**Issue by indolering** [PolymerLabs/polybuild#11]
PolyBuild throws an error when trying to build an element that includes a JS library using a canonical path.

In `my-element.html`:

```
<script src="../js-library/js-library.js" type="application/javascript"></script>
```

Output from Gulp command that uses `polybuild`:

```
Message:
  ENOENT: no such file or directory, open '/Users/user/my-element-parent-directory/js-library/js-library.js'
Details:
  errno: -2
  code: ENOENT
  syscall: open
  path: /Users/user/my-element-parent-directory/js-library/js-library.js
  fileName: /Users/user/my-element-parent-directory/my-element/my-element.html
```
