### ISSUE TITLE
Data URI's fail after polybuild

### ISSUE THREAD

**Issue by rubenstolk** [PolymerLabs/polybuild#14]
When any of the elements has a CSS statement like:

``` css
.background {
  background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAAAAACIM/FCAAAC0klEQVR42u3b626qQBSG4d7WCBPaQhMFQrS1HKLYUqkMzLr/3/v3TrZuziwm33sD5gkoh7V8Eob0BAgggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCArh7hRnJdKk1ZlHkfuOiF2eFL0d+oU2muDuGlD/6pJ3TVB3Jzul7trgchE06N0IlcB8RX9L+Xzh1gxtSm2mENkQe0qJGuIU1LbSocxxLlR+24OW4j8pS79SqYQq6BuFRZPSExdS1hCfOqezxAiVQ+IkvwgGfUpYwdxdS+IdrlBcupXzgziUt9cXpCsNyRjBbGb3pDG5gQJqX8hJ8h5AOTMCLKpB0DqDR+IR0Py+ECiQZCIDyQeBIn5QPJBkJwPpBwEKflA1CBIxQeiB0FqPhAaFo4IviPG/2oZcx0x5spuzL2WMXe/xjyPGPOEKIIBkIATxOp/btUWJ4hIe0NSvGnEu9/Hl5Keb+M9bhBj5iPmTKyMmSEKkRgy1TVnzm7M5oMQz512UZ4FW4gx20Hm7GuZs0EnjNlpFOZsmQoh3PN9ij6vZu9XCCFeszub2NnrNB+I3fh2p1gU52VVr/vfCnMHCCCAAAIIIIAAAgggS0Gct2D/mV2K600pTaSVul2LS/a5D96clUBe/PfT9eFidnM9ffgvnCFyd/xqPRWtv447yRBibeOfzkMr/RNvLU4QJ7r03vJvLpHDA+LsCxpYsXeWhljht6YR0t+htSDEy2oarTrzloFsgoJGrgg2s0PsQ0UTVB3sWSHyo6aJqo9yNoh9bGjCmqM9C8Q61DRx9cGaHhJUNENVMDHEK2imCm9CiJ1omi2d2FNB/IpmrfIngcgTzd5Zjg/ZVrRA1W5sSEoLlY4MocUCBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQABZBPIHh56A4BJsHpMAAAAASUVORK5CYII=');
}
```

After loading the application when built with polybuild, the browser tries to load:

`http://localhost:3001/data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAAAAACIM/FCAAAC0klEQVR42u3b626qQBSG4d7WCBPaQhMFQrS1HKLYUqkMzLr/3/v3TrZuziwm33sD5gkoh7V8Eob0BAgggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCArh7hRnJdKk1ZlHkfuOiF2eFL0d+oU2muDuGlD/6pJ3TVB3Jzul7trgchE06N0IlcB8RX9L+Xzh1gxtSm2mENkQe0qJGuIU1LbSocxxLlR+24OW4j8pS79SqYQq6BuFRZPSExdS1hCfOqezxAiVQ+IkvwgGfUpYwdxdS+IdrlBcupXzgziUt9cXpCsNyRjBbGb3pDG5gQJqX8hJ8h5AOTMCLKpB0DqDR+IR0Py+ECiQZCIDyQeBIn5QPJBkJwPpBwEKflA1CBIxQeiB0FqPhAaFo4IviPG/2oZcx0x5spuzL2WMXe/xjyPGPOEKIIBkIATxOp/btUWJ4hIe0NSvGnEu9/Hl5Keb+M9bhBj5iPmTKyMmSEKkRgy1TVnzm7M5oMQz512UZ4FW4gx20Hm7GuZs0EnjNlpFOZsmQoh3PN9ij6vZu9XCCFeszub2NnrNB+I3fh2p1gU52VVr/vfCnMHCCCAAAIIIIAAAgggS0Gct2D/mV2K600pTaSVul2LS/a5D96clUBe/PfT9eFidnM9ffgvnCFyd/xqPRWtv447yRBibeOfzkMr/RNvLU4QJ7r03vJvLpHDA+LsCxpYsXeWhljht6YR0t+htSDEy2oarTrzloFsgoJGrgg2s0PsQ0UTVB3sWSHyo6aJqo9yNoh9bGjCmqM9C8Q61DRx9cGaHhJUNENVMDHEK2imCm9CiJ1omi2d2FNB/IpmrfIngcgTzd5Zjg/ZVrRA1W5sSEoLlY4MocUCBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQABZBPIHh56A4BJsHpMAAAAASUVORK5CYII=` as url.

Everything works fine when the app is not built with polybuild.

I'm fearing for a very weird issue which might also be related to #13 since we're talking about `url`.
